#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/trackerGST.jar:$APPDIR/lib/core.jar:$APPDIR/lib/video.jar:$APPDIR/lib/blobDetection.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/GSVideo.jar" trackerGST
